const point=(label,x,z,h=15,seconds=2)=>({kind:'point',label,x,z,h,radius:6,tolerance:4,seconds});
const mode=(label,value,seconds=6)=>({kind:'mode',label,value,seconds});
const auto=(value,seconds=8)=>({kind:'auto',label:`Demonstrar ${value} por ${seconds} s`,value,seconds});
const photo=(label,x,z,h)=>({kind:'photo',label,x,z,h,radius:65,seconds:0});
const land={kind:'land',label:'Pousar na base H sem colisão',radius:12,seconds:1};
const configs=[
 {id:'primeiro-voo',title:'Primeiro voo',scene:'field',brief:'Decole, estabilize a aeronave sobre H e visite os marcadores na ordem. Use W/S para altitude, A/D para giro e setas para deslocamento. Volte e pouse na base.',goals:[point('Pairar 20 s acima da base',0,0,12,20),point('Visitar o marcador 2',20,-25),point('Visitar o marcador 3',-20,-45),land]},
 {id:'precisao',title:'Circuito de precisão',scene:'course',brief:'Atravesse os seis portais em ordem. Demonstre Cine, Normal e Sport nas etapas indicadas. Sport não oferece assistência de obstáculos.',goals:[mode('Demonstrar Cine','Cine'),point('Portal 1',0,-25,12),point('Portal 2',25,-45,18),mode('Demonstrar Normal','Normal'),point('Portal 3',45,-15,22),point('Portal 4',25,20,18),mode('Demonstrar Sport em área livre','Sport'),point('Portal 5',-20,25,15),point('Portal 6',-25,-10,12),land]},
 {id:'solar',title:'Telhado para instalação solar',scene:'roof',brief:'Inspecione o telhado azul a norte da base. Aproxime-se com segurança, use gimbal e zoom e fotografe os quatro marcadores laranja na ordem. O alvo deve estar centralizado na câmera, a menos de 65 m.',goals:[{kind:'setting',label:'Ajustar zoom para pelo menos 1,5×',key:'zoom',minimum:1.5,seconds:1},{kind:'setting',label:'Selecionar exposição Pro',key:'exposure',value:'Pro',seconds:1},photo('Fotografar face sul',0,-62,14),photo('Fotografar face leste',17,-77,14),photo('Fotografar face norte',0,-92,14),photo('Fotografar obstáculo no telhado',-12,-77,18),land]},
 {id:'area',title:'Inspeção de área',scene:'survey',brief:'Planeje uma rota no mapa com os seis setores, execute Waypoints e visite os marcadores. A rota pode ser editada no menu WP. Supervisione e finalize com retorno à base.',goals:[auto('Waypoints'),point('Setor 1',0,-30,25),point('Setor 2',35,-30,25),point('Setor 3',35,-70,25),point('Setor 4',0,-70,25),point('Setor 5',-35,-70,25),point('Setor 6',-35,-30,25),auto('rth',3),land]},
 {id:'evento',title:'Cobertura de evento',scene:'event',brief:'Faça uma tomada em Cine por 10 s com gravação ativa e demonstre Dronie, Rocket e Circle. O veículo é a referência dos QuickShots. A região vermelha representa público: não sobrevoe.',goals:[{kind:'video',label:'Gravar 10 s em Cine',value:'Cine',seconds:10},auto('Dronie'),auto('Rocket'),auto('Circle'),land]},
 {id:'torre',title:'Inspeção de torre',scene:'tower',brief:'A torre está a norte da base. Registre os quatro marcadores em alturas diferentes. Mantenha distância da estrutura e prepare os sensores antes do voo.',goals:[{kind:'setting',label:'Configurar sensores para Frear',key:'avoid',value:'Frear',seconds:1},photo('Inspecionar base da torre',0,-56,8),photo('Inspecionar nível intermediário',0,-56,24),photo('Inspecionar antena superior',0,-56,44),photo('Inspecionar módulo lateral',6,-60,30),land]},
 {id:'fachada',title:'Inspeção de fachada',scene:'facade',brief:'Faça o roteiro de calibração antes de voar. Fotografe os defeitos sinalizados na fachada. Na última tomada a iluminação diminui: redobre o controle manual e mantenha distância.',goals:[{kind:'calibration',label:'Concluir um roteiro de calibração em solo',seconds:0},photo('Fotografar fissura esquerda',-15,-70,10),photo('Fotografar fissura central',0,-70,20),photo('Fotografar fissura direita em pouca luz',15,-70,12),land]},
 {id:'obra',title:'Acompanhamento de obra',scene:'construction',brief:'Registre os quatro pontos da obra e demonstre Helix, Boomerang e Asteroid em área livre, usando o veículo como referência. As manobras são aproximações didáticas.',goals:[photo('Registrar fundação',-25,-60,2),photo('Registrar estrutura',0,-75,16),photo('Registrar cobertura',25,-70,22),photo('Registrar acesso',30,-35,2),auto('Helix'),auto('Boomerang'),auto('Asteroid'),land]},
 {id:'busca',title:'Busca em área rural',scene:'rural',brief:'Faça a busca pelos três setores. Localize o veículo laranja, selecione-o e use ActiveTrack por 15 s. Cancele a automação e retorne.',goals:[point('Buscar setor 1',-35,-30,25),point('Buscar setor 2',-35,-70,25),point('Buscar setor 3',30,-90,25),auto('track',15),{kind:'manual',label:'Retomar controle manual por 5 s',seconds:5},land]},
 {id:'contingencia',title:'Missão com contingências',scene:'emergency',brief:'Antes de iniciar, configure perda de enlace para Pairar. Decole e estabilize. O sistema introduz perda de enlace, GNSS fraco, vento e bateria baixa. A recuperação dos sinais e a confirmação da origem serão simuladas pelo exercício antes da bateria baixa.',goals:[point('Estabilizar sobre a base',0,0,15,5),{kind:'link',label:'Manter pairado durante perda de enlace (8 s)',seconds:8},{kind:'gps',label:'Controlar com GNSS fraco e vento (8 s)',seconds:8},auto('rth',3),land]}
];
export const courseMissions=configs.map((m,i)=>({...m,order:i+1,version:1,maxScore:100,maxDuration:1800,maxHeight:100,maxDistance:400,initial:{mode:'Normal',rthH:50,maxH:100,maxD:400},zones:m.id==='evento'?[{x:-55,z:-65,radius:20}]:[],quiz:{question:'Qual condição exige interromper a operação?',choices:['Área isolada e origem confirmada','Pessoas entrando na área de operação','Bateria conferida e rota revisada'],answer:1}}));
export const missionById=id=>courseMissions.find(m=>m.id===id);
export const preChecklist=['Área de voo e pessoas verificadas','Estrutura e hélices inspecionadas','Bateria suficiente','GNSS e origem confirmados','Limites e RTH revisados','Sensores e condições de luz avaliados'];
export const postChecklist=['Pouso confirmado','Motores parados','Equipamento desligado','Inspeção pós-voo concluída','Capturas conferidas','Ocorrências registradas'];
